[workspace]
members = ["crates/*", "examples/breakout", "examples/simple"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.15.0-rc.3", default-features = false, features = [
    "bevy_remote",
    "serialize",
] }
serde = "1"
serde_json = "1"
anyhow = "1"

[profile.dev]
debug = 0
