[package]
name = "bevy_remote_inspector2"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[features]
default = ["bevy_render"]
bevy_render = ["bevy/bevy_render"]
